DROP DATABASE IF EXISTS mentor_db;
CREATE DATABASE mentor_db;

CREATE TABLE USER_INFO (
    id INT NOT NULL AUTO_INCREMENT,
    email VARCHAR(50) NOT NULL,
    pass VARCHAR(50) NOT NULL,
    title VARCHAR(50) NOT NULL,
    PRIMARY KEY (id)
);